function simulate

% This is a simple program to simulate the gait2dem model.
% It does not anything particularly interesting, and is mainly
% intended as a template for further software development.

	% Some constants
	ndof = 9;
	nmom = 6;
	nstates = 2*ndof;

	% Set initial condition, a sort of squatting posture
	xinit = zeros(nstates,1);
	xinit(1:9) = [0 0.68 -pi/4 pi/2 -pi/2 pi/4 pi/2 -pi/2 pi/4];

	% Simulation settings
	duration = 3.0;									% duration in seconds
	outputinterval = 0.04;							% time between output samples
	outputgrid = [0:outputinterval:duration];		% time grid for output

	% Run the simulation
	[t,x] = ode23(@odefun, outputgrid, xinit);
	disp('simulation finished, creating animation...');
	anim(x');
	fprintf('Maximum hip height: %8.4f m\n', max(x(:,2)) );

end
%=====================================================================================
function [xdot] = odefun(t,x);
	tau = [zeros(3,1); controller(t,x)];		% six joint torques are generated by a controller
	xdot = gait2dem(x,tau);
end
%=====================================================================================
function [u] = controller(t,x);
	% example of a controller
	Kp = [100 100 100 100 100 100]';		% proportional feedback gains for each joint
	setpoints = zeros(6,1);				% setpoint: all angles zero
	u = -Kp .* (x(4:9) - setpoints);   	% control law (x(4:9) are the six joint angles)
end
%=====================================================================================